// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDfehkSHj1aYjoSQ9ZGE6U56IeM_qhzmI',
    appId: '1:389807237400:web:5a27fc058ee5060c83166d',
    messagingSenderId: '389807237400',
    projectId: 'hometaskappdb',
    authDomain: 'hometaskappdb.firebaseapp.com',
    storageBucket: 'hometaskappdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq3TLuNy4Tt8Mq_wvSb1DwYSF4l6SY7R0',
    appId: '1:389807237400:android:7b0a755555c8cc3983166d',
    messagingSenderId: '389807237400',
    projectId: 'hometaskappdb',
    storageBucket: 'hometaskappdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrumg_gVhe4AJEMB183auzznMPxvbODzg',
    appId: '1:389807237400:ios:03a2f37c42f15c0883166d',
    messagingSenderId: '389807237400',
    projectId: 'hometaskappdb',
    storageBucket: 'hometaskappdb.appspot.com',
    iosClientId: '389807237400-rg9pearcmnhapi559gfggomc9kqmifem.apps.googleusercontent.com',
    iosBundleId: 'com.dmitrykozlov.hometasksapp',
  );
}
